name: flutter_wananzhuo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 网络请求库
  dio: ^2.1.13
  # Cookie持久化
  cookie_jar: ^1.0.0
  # 轮播图组件
  flutter_swiper: ^1.1.6
  # 屏幕适配
  flutter_screenutil: ^0.5.3
  # 下拉刷新上拉加载更多
  flutter_easyrefresh: ^2.0.2
  # provider状态管理
  provider: ^3.0.0+1
  # toast提示
  fluttertoast: ^3.1.0
  # WebView插件
  webview_flutter: ^0.3.13
  # svg插件  主要为了代码实践，所以有些图使用png，有些图使用svg
  flutter_svg: ^0.12.4+2
  # 使用小存储文件存储数据
  shared_preferences: ^0.5.3+4
  # 访问手机文件系统
  path_provider: ^1.2.0
  # IOS风格日期时间选择控件
  flutter_cupertino_date_picker: ^1.0.12
  # 日期时间格式化
  date_format: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/default_avatar.png
   - images/todo_red.png
   - images/todo.png
   - images/untodo_red.png
   - images/untodo.png
   - images/delete.png
   - images/complete.png
   - images/uncomplete.png
   - images/done.png
   - images/net_error.png
   - assets/wechat.svg
   - assets/collection.svg
   - assets/about.svg
   - assets/logout.svg
   - assets/settings.svg
   - assets/todo.svg
   - assets/waps.svg
   - assets/open_source.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
